server:
  port: "8080"

database:
  host: "postgres"         
  port: "5432"
  user: "shorty_user"
  password: "Brij@8123"
  name: "shorty"
  sslmode: "disable"

redis:
  host: "redis"            
  port: "6379"
  password: ""
  db: 0
  pool_size: 10

jwt:
  secret: "supersecretkey_change_me"
  issuer: "url-shortener"
  access_token_expiry_minutes: 60
  refresh_token_expiry_hours: 168
